// Auto-generated from CRCR Study Guides (Weeks 1-6) + Training Documents
// Total: 90+ questions across 3 difficulty levels
// Each question includes an explanation for learning

const EXPANDED_TRIVIA = {
  "apprentice": [
    {"question": "What does EOB stand for?", "answers": ["Explanation of Benefits", "End of Billing", "Electronic Order Batch", "Estimate of Balance"], "correct": 0, "explanation": "An EOB is sent by the insurance company explaining how a claim was processed and paid."},
    {"question": "What does ERA stand for?", "answers": ["Electronic Remittance Advice", "Employer Revenue Account", "Escalation Review Alert", "Enrollment Registration Activity"], "correct": 0, "explanation": "An ERA is the electronic version of an EOB, received digitally for faster payment posting."},
    {"question": "What does CARC stand for?", "answers": ["Claim Adjustment Reason Code", "Clinical Authorization Review Code", "Cost Allocation Revenue Category", "Compliance Audit Report Card"], "correct": 0, "explanation": "CARCs give a broad reason for why a claim was adjusted or denied."},
    {"question": "What does RARC stand for?", "answers": ["Remittance Advice Remark Code", "Revenue Allocation Resource Code", "Regulatory Audit Review Checklist", "Reimbursement Authorization Request Code"], "correct": 0, "explanation": "RARCs provide specific explanations. CARC = the 'what', RARC = the 'why'."},
    {"question": "How many steps are in the RCM journey?", "answers": ["8", "10", "12", "15"], "correct": 2, "explanation": "The RCM process has 12 steps from preregistration to collections and follow-up."},
    {"question": "Which step comes FIRST in the RCM cycle?", "answers": ["Charge Capture", "Preregistration & Scheduling", "Insurance Verification", "Claim Submission"], "correct": 1, "explanation": "The patient journey begins with preregistration and scheduling."},
    {"question": "What is the primary document for understanding claim status?", "answers": ["Insurance card", "EOB/ERA", "Patient chart", "Provider notes"], "correct": 1, "explanation": "The EOB/ERA is the 'report card' of a claim showing what was billed, allowed, and paid."},
    {"question": "What does 'Charge Capture' mean in RCM?", "answers": ["Collecting co-pays", "Documenting all services rendered after a visit", "Sending claims to insurance", "Posting payments"], "correct": 1, "explanation": "After the visit, providers document all services rendered for billing."},
    {"question": "What does 'Payer Adjudication' mean?", "answers": ["Patient pays their bill", "Insurance processes and decides how to pay the claim", "Provider appeals a denial", "Claim is submitted electronically"], "correct": 1, "explanation": "Adjudication is when the insurance company reviews and determines payment."},
    {"question": "What is a 'clean claim'?", "answers": ["A claim paid on first attempt without errors", "A claim paid in full", "A claim with no patient balance", "A claim on paper"], "correct": 0, "explanation": "A clean claim passes all checks and is paid on first submission without manual intervention."},
    {"question": "The adjustment group code 'PR' means:", "answers": ["Provider Responsibility", "Patient Responsibility", "Payer Reimbursement", "Prior Review"], "correct": 1, "explanation": "PR means the patient owes this portion (co-pays, deductibles, coinsurance)."},
    {"question": "The adjustment group code 'CO' means:", "answers": ["Collection Order", "Contractual Obligation", "Compliance Override", "Coding Omission"], "correct": 1, "explanation": "CO means the adjustment is due to a contract between provider and payer."},
    {"question": "What is a 'clearinghouse' in RCM?", "answers": ["A building for claims storage", "A third-party that routes electronic claims to payers", "A department that fixes denials", "A payer's review team"], "correct": 1, "explanation": "Claims are sent electronically through a clearinghouse that routes them to the correct payer."},
    {"question": "What does 'PI' mean as an adjustment group code?", "answers": ["Patient Insurance", "Payer Initiated", "Prior Information", "Pending Investigation"], "correct": 1, "explanation": "PI means the payer made a unilateral adjustment (e.g., found a duplicate claim)."},
    {"question": "What are the THREE phases of the revenue cycle?", "answers": ["Pre-Service, Time of Service, Post-Service", "Billing, Coding, Collections", "Intake, Processing, Output", "Registration, Treatment, Payment"], "correct": 0, "explanation": "The revenue cycle operates in three interdependent phases: Pre-Service, Time of Service, Post-Service."},
    {"question": "What is a 'premium' in health insurance?", "answers": ["A bonus for good health", "The monthly fee paid to maintain active coverage", "The amount a patient owes after a visit", "A type of insurance plan"], "correct": 1, "explanation": "A premium is the monthly payment to keep insurance coverage active, often deducted from paychecks."},
    {"question": "What happens during 'Pre-Service'?", "answers": ["Patient receives care", "Claims are submitted", "Insurance is verified and authorization is obtained", "Payments are posted"], "correct": 2, "explanation": "Pre-Service includes scheduling, eligibility verification, prior auth, and financial counseling."},
    {"question": "Most Americans get health insurance through:", "answers": ["The government", "Their employer", "Direct purchase only", "Hospitals"], "correct": 1, "explanation": "Most Americans receive insurance through employer-sponsored plans with premiums deducted from paychecks."},
    {"question": "What does VOB stand for?", "answers": ["Verification of Benefits", "Volume of Billing", "Validation of Balance", "Vendor Order Batch"], "correct": 0, "explanation": "VOB determines exact coverage details and patient cost-sharing (deductible, copay, coinsurance)."},
    {"question": "What is the Clean Claim Rate?", "answers": ["Percentage of claims with no errors", "Percentage of claims paid on first submission", "Percentage of claims under $100", "Percentage of claims filed on time"], "correct": 1, "explanation": "Clean Claim Rate = claims paid on first attempt / total claims submitted. Higher is better."}
  ],

  "journeyman": [
    {"question": "What is the 'Allowed Amount' on an EOB?", "answers": ["What the provider billed", "Maximum amount the payer agreed to pay", "What the patient owes", "Total claim value"], "correct": 1, "explanation": "The Allowed Amount is the contracted maximum the payer will reimburse for that service."},
    {"question": "Billed Amount minus Allowed Amount equals:", "answers": ["Patient responsibility", "Contractual write-off", "Denial amount", "Co-pay"], "correct": 1, "explanation": "The difference is the contractual adjustment (CO code) written off per the provider-payer contract."},
    {"question": "A denial for 'no prior authorization' means:", "answers": ["Wrong demographics", "Service needed pre-approval that wasn't obtained", "Claim filed too late", "Provider is out of network"], "correct": 1, "explanation": "The payer required prior approval before the service was performed, and it wasn't secured."},
    {"question": "What does HIPAA stand for?", "answers": ["Health Insurance Portability and Accountability Act", "Healthcare Information Privacy and Access Act", "Hospital Insurance Payment and Audit Act", "Health Information Protection and Authorization Act"], "correct": 0, "explanation": "HIPAA is the federal foundation of patient privacy, governing how PHI is accessed and shared."},
    {"question": "What is PHI?", "answers": ["Public Health Index", "Protected Health Information", "Patient Hospital Invoice", "Physician Health Insurance"], "correct": 1, "explanation": "PHI is any individually identifiable health information in any form (electronic, paper, or oral)."},
    {"question": "TPO in HIPAA stands for:", "answers": ["Treatment, Payment, and Operations", "Third-Party Organization", "Technical Privacy Officer", "Total Patient Obligation"], "correct": 0, "explanation": "TPO is the core HIPAA exception allowing revenue cycle staff to share PHI for treatment, payment, and operations."},
    {"question": "The HIPAA 'Minimum Necessary Standard' means:", "answers": ["Use the cheapest treatment", "Access only the minimum PHI needed for your specific job task", "Provide minimum care to patients", "Bill the minimum amount"], "correct": 1, "explanation": "Staff must only access the absolute minimum amount of PHI required to perform their specific task."},
    {"question": "What are the three HIPAA safeguard categories?", "answers": ["Administrative, Physical, Technical", "Legal, Financial, Clinical", "Privacy, Security, Compliance", "Internal, External, Digital"], "correct": 0, "explanation": "Administrative = policies/training, Physical = locks/screens, Technical = encryption/passwords."},
    {"question": "A HIPAA breach must be reported within:", "answers": ["24 hours", "30 days", "60 days", "90 days"], "correct": 2, "explanation": "Affected individuals must be notified within 60 days of discovering a breach."},
    {"question": "FDCPA stands for:", "answers": ["Fair Debt Collection Practices Act", "Federal Department of Claims Processing Authority", "Financial Data Control and Privacy Act", "Fair Disclosure and Consumer Protection Act"], "correct": 0, "explanation": "FDCPA protects patients from abusive or unfair debt collection practices."},
    {"question": "Under FDCPA, collectors cannot call patients:", "answers": ["On weekends", "Before 8am or after 9pm", "More than once per week", "At their workplace without permission"], "correct": 1, "explanation": "FDCPA restricts calls to between 8am and 9pm in the patient's local time zone."},
    {"question": "What is 'Assignment of Benefits' (AOB)?", "answers": ["Patient assigns their doctor", "Patient authorizes insurance payments to go directly to the provider", "Patient assigns a representative", "Provider assigns a billing code"], "correct": 1, "explanation": "AOB is a legal document where the patient directs their insurance to pay the provider directly."},
    {"question": "What is 'Point-of-Service (POS) Collections'?", "answers": ["Collecting payments while patient is present at the facility", "Collecting data about the service", "Post-service billing", "Provider payment"], "correct": 0, "explanation": "POS collections = collecting copays and balances while the patient is physically present. Most effective collection method."},
    {"question": "What is a 'Chargemaster'?", "answers": ["The person in charge of billing", "A comprehensive list of all billable items and their prices", "A credit card processing system", "A charge capture device"], "correct": 1, "explanation": "The Chargemaster is a master price list containing every supply, procedure, and service a facility can bill for."},
    {"question": "CMS-1500 is used for:", "answers": ["Institutional claims (hospitals)", "Professional claims (physicians/outpatient)", "Medicare enrollment", "Patient registration"], "correct": 1, "explanation": "CMS-1500 is the standard form for professional (physician/outpatient) claims. UB-04 is for institutional."},
    {"question": "UB-04 is used for:", "answers": ["Professional claims", "Institutional claims (hospitals/facilities)", "Patient billing statements", "Insurance enrollment"], "correct": 1, "explanation": "UB-04 is the standard form for institutional (hospital/facility) claims. CMS-1500 is for professional."},
    {"question": "What does 'Coinsurance' mean?", "answers": ["A second insurance plan", "Patient's percentage share after deductible is met", "Late payment penalty", "Provider's cost share"], "correct": 1, "explanation": "Coinsurance is the patient's percentage (e.g., 20%) after their deductible has been satisfied."},
    {"question": "What is the 'Out-of-Pocket Maximum'?", "answers": ["Maximum a patient pays before insurance covers 100%", "Maximum a provider can charge", "Maximum insurance premium", "Maximum number of visits per year"], "correct": 0, "explanation": "Once a patient hits their OOP max, insurance covers 100% of covered services for the rest of the plan year."}
  ],

  "master": [
    {"question": "The 'Tiered Problem-Solving framework' helps analysts:", "answers": ["Calculate balances", "Categorize denials by complexity for resolution strategy", "Write appeal letters", "Submit claims faster"], "correct": 1, "explanation": "The Tiered framework helps strategically approach denials based on their complexity level."},
    {"question": "Resubmission vs. Appeal — the key difference:", "answers": ["Resubmissions cost more", "Resubmission corrects OUR error; Appeal challenges the PAYER'S decision", "Appeals are faster", "No difference"], "correct": 1, "explanation": "Resubmission = we made a mistake. Appeal = we disagree with the payer's decision."},
    {"question": "When should you escalate a claim?", "answers": ["After every denial", "When standard paths are exhausted or timely filing is at risk", "Only when a manager asks", "Never"], "correct": 1, "explanation": "Escalate when standard paths fail or delay risks timely filing deadlines."},
    {"question": "An effective appeal letter must include:", "answers": ["Emotional language", "Clinical justification citing the specific payer policy disputed", "Threats of legal action", "Patient's financial situation"], "correct": 1, "explanation": "Effective appeals include clinical documentation, policy references, and clear justification."},
    {"question": "A 'Reversal' (recoupment) means:", "answers": ["Patient reverses insurance", "Payer takes back money previously paid", "Provider cancels a service", "Appeal is overturned"], "correct": 1, "explanation": "A reversal is when a payer takes back previously paid funds, requiring investigation."},
    {"question": "First thing to check when you receive a denial:", "answers": ["Call the payer", "Read the CARC/RARC codes to understand WHY", "Write an appeal", "Transfer to another team"], "correct": 1, "explanation": "Always start with CARC/RARC codes. They tell you exactly what went wrong."},
    {"question": "What is 'AR Aging'?", "answers": ["Patient's age", "How long claims have been outstanding without payment", "Age of provider's contract", "Time since last audit"], "correct": 1, "explanation": "AR Aging measures how long accounts receivable claims have been waiting for payment."},
    {"question": "What does 'Collections Yield' measure?", "answers": ["Number of calls", "Percentage of billed charges actually collected", "Patient satisfaction", "Claims submitted"], "correct": 1, "explanation": "Collections yield = total collected / total billed. Measures revenue recovery effectiveness."},
    {"question": "The Post-Service flow in correct order is:", "answers": ["Payment > Denial > Submission > Patient Billing", "Submission > Adjudication > Payment Posting > Denial Management", "Denial > Appeal > Payment > Collections", "Coding > Submission > Payment > Audit"], "correct": 1, "explanation": "Correct flow: Claim Submission > Clearinghouse > Adjudication > Payment Posting > Denial Management."},
    {"question": "A breach affecting 500+ individuals requires:", "answers": ["Only internal reporting", "Notification to individuals AND media AND HHS", "Just notifying the patients", "No action if unintentional"], "correct": 1, "explanation": "Breaches of 500+ require notifying affected individuals, prominent media outlets, AND HHS within 60 days."},
    {"question": "The 'Validation of Debt' under FDCPA requires:", "answers": ["Calling the patient to validate", "Sending written notice within 5 days of first contact with amount owed and creditor name", "Court approval before collecting", "Manager sign-off on every call"], "correct": 1, "explanation": "FDCPA requires written validation notice within 5 days of initial contact, stating amount and creditor."},
    {"question": "If a Pre-Service error occurs (wrong subscriber ID), it creates:", "answers": ["No impact", "A demographic denial downstream that could have been prevented", "An immediate payment", "A coding error"], "correct": 1, "explanation": "Pre-Service errors compound downstream. A typo in subscriber ID = denial at adjudication."},
    {"question": "What connects daily analyst work to KPIs?", "answers": ["Attendance", "Each resolved claim directly improves denial rate, AR aging, and yield", "Email volume", "Meeting count"], "correct": 1, "explanation": "Every claim resolved impacts team KPIs. Individual work drives department financial outcomes."},
    {"question": "'Days in AR' benchmark for the industry is:", "answers": ["10-20 days", "35-45 days", "60-90 days", "120+ days"], "correct": 1, "explanation": "Industry benchmark for Days in AR is 35-45 days. Lower is better."},
    {"question": "A low Clean Claim Rate signals:", "answers": ["Good performance", "Upstream data quality problems compounding into denials", "Fast payment", "Efficient coding"], "correct": 1, "explanation": "Low Clean Claim Rate = upstream errors (demographics, missing auths) creating downstream denials."},
    {"question": "What is 'First Contact Resolution' (FCR)?", "answers": ["First time filing a claim", "Resolving a patient inquiry completely on the first interaction", "First denial appeal", "Initial patient registration"], "correct": 1, "explanation": "FCR = resolving the issue on first contact without callbacks or transfers. Drives patient satisfaction and efficiency."},
    {"question": "'General Consent for Treatment' allows:", "answers": ["The facility to bill insurance", "The facility to provide routine medical care", "The patient to choose their doctor", "Insurance to deny claims"], "correct": 1, "explanation": "General Consent gives legal permission to provide routine care. Different from Informed Consent for specific procedures."},
    {"question": "What is 'revenue leakage' from missing charges?", "answers": ["Insurance paying too much", "Services delivered but never billed due to undocumented care", "Patient overpayment", "Coding upcoding"], "correct": 1, "explanation": "If clinical team forgets to document a service, it becomes a 'missing charge' = permanent lost revenue."}
  ]
};
