// Scenario-Based Questions (CRCR Exam Style)
// Each question presents a real-world situation and asks what the analyst should do.
// These test critical thinking, not memorization.

const SCENARIO_TRIVIA = {
  "apprentice": [
    {"question": "A patient calls saying they received a bill for $2,400 but thought their insurance covered the visit. You pull up the EOB and see the adjustment code is 'PR' with a note about the deductible. What do you explain?", "answers": ["Their insurance denied the claim", "The $2,400 is their deductible responsibility — insurance processed the claim but this amount applies to their annual deductible", "There was a billing error", "They need to call their insurance company"], "correct": 1, "explanation": "PR (Patient Responsibility) with a deductible note means insurance processed correctly but the patient hasn't met their deductible yet. The amount is legitimately owed by the patient."},
    {"question": "You're verifying a patient's insurance before their appointment tomorrow. The system shows their policy terminated 2 weeks ago. What is your next step?", "answers": ["Proceed with the appointment anyway", "Contact the patient to confirm current coverage and collect updated insurance information", "Cancel the appointment", "Submit the claim to the old insurance"], "correct": 1, "explanation": "Pre-Service verification caught the issue. Contact the patient to get current coverage info BEFORE the visit, preventing a 'Patient Not Eligible' denial downstream."},
    {"question": "A new claim comes back from the clearinghouse rejected for 'invalid subscriber ID.' Where did the error most likely originate?", "answers": ["Medical Coding", "Pre-Registration/Patient Access", "The payer's system", "Payment Posting"], "correct": 1, "explanation": "Invalid subscriber ID is a demographic error from Pre-Registration. Someone likely mistyped the member ID during intake. This is why Pre-Service accuracy matters."},
    {"question": "You see a claim with Billed Amount: $500, Allowed Amount: $350, Paid Amount: $280, and PR amount: $70. How much is the contractual write-off?", "answers": ["$70", "$150", "$220", "$280"], "correct": 1, "explanation": "Contractual write-off = Billed ($500) minus Allowed ($350) = $150. This is the CO (Contractual Obligation) amount written off per the provider-payer contract."},
    {"question": "A colleague asks to see a patient's full medical record because they're 'curious about the diagnosis.' What should you do?", "answers": ["Show them the record since you're coworkers", "Deny access — this violates HIPAA's Minimum Necessary Standard", "Ask your manager first", "Only show the billing section"], "correct": 1, "explanation": "HIPAA's Minimum Necessary Standard: staff may only access PHI required for their specific job task. Curiosity is not a valid reason."},
    {"question": "It's the patient's first visit. At check-in, which document must they sign to allow insurance payments to go directly to the provider?", "answers": ["HIPAA Notice of Privacy Practices", "Assignment of Benefits (AOB)", "General Consent for Treatment", "Financial Responsibility Agreement"], "correct": 1, "explanation": "The AOB directs the patient's insurance to pay the provider directly instead of reimbursing the patient."},
    {"question": "A patient's copay is $40. They're at the front desk ready to leave. When is the BEST time to collect this?", "answers": ["Send a statement later", "Now, at Point-of-Service while they're present", "After insurance processes the claim", "Only if they ask about it"], "correct": 1, "explanation": "POS (Point-of-Service) collection while the patient is present is the most effective method. After they leave, collection rates drop significantly."},
    {"question": "You notice a provider saw a patient but the encounter shows $0 in charges. What likely happened?", "answers": ["Insurance already paid", "The visit was free", "Clinical team failed to document services — this is revenue leakage", "The patient has 100% coverage"], "correct": 2, "explanation": "A documented visit with $0 charges = missing charge capture. Services were delivered but never translated into billable codes. This is permanent revenue loss."}
  ],

  "journeyman": [
    {"question": "A claim is denied with CARC 197: 'Precertification/authorization/notification absent.' The service was performed 3 weeks ago. What's your resolution path?", "answers": ["Write it off — too late", "Submit a retroactive authorization request to the payer with clinical documentation supporting medical necessity", "Resubmit the claim as-is", "Bill the patient"], "correct": 1, "explanation": "Many payers allow retroactive auth requests within a window. Submit with clinical documentation proving medical necessity. Don't write off without attempting."},
    {"question": "You're posting an ERA and notice the payer recouped $1,200 from a claim paid 4 months ago, citing 'duplicate payment.' What should you do?", "answers": ["Accept the recoupment without question", "Research the original claim to verify if it truly was a duplicate before accepting the takeaway", "Immediately appeal", "Bill the patient $1,200"], "correct": 1, "explanation": "Never accept recoupments blindly. Research whether it was actually a duplicate. If not, dispute with documentation showing the claims were for different dates/services."},
    {"question": "A patient's claim was denied for 'timely filing' — submitted 95 days after service. Your payer contract allows 90 days. What's your best option?", "answers": ["Write it off — deadline passed", "Check if you have proof of a prior submission attempt (clearinghouse receipt, rejection notice) that would reset the clock", "Appeal citing patient hardship", "Resubmit and hope they don't notice"], "correct": 1, "explanation": "If you have evidence of a prior timely submission (even if rejected), this proves timely filing intent. Many payers will accept a corrected resubmission with proof of original attempt."},
    {"question": "You receive a call from someone claiming to be the patient's spouse, requesting account balance information. What must you verify FIRST?", "answers": ["Their relationship to the patient", "Whether the patient has a signed authorization on file allowing disclosure to this person", "The caller's address", "Nothing — spouses can always access info"], "correct": 1, "explanation": "Under HIPAA, you can only share PHI with authorized individuals. Check for a signed authorization form. Spousal relationship alone doesn't guarantee access rights."},
    {"question": "A payer adjudicates a claim and pays $0, with CARC CO-4: 'The procedure code is inconsistent with the modifier used.' What team likely caused this?", "answers": ["Collections", "Medical Coding — they applied an incorrect modifier", "Patient Access", "Cash Application"], "correct": 1, "explanation": "CO-4 (modifier inconsistency) is a coding error. The coder applied a modifier that doesn't match the procedure. Resolution: correct the code and resubmit."},
    {"question": "A patient calls furious about a $3,000 bill. They say 'I have insurance!' You pull up the account and see the claim was never submitted. What happened?", "answers": ["Insurance denied it", "The claim failed clearinghouse scrubbing due to errors and was never sent to the payer", "The patient's insurance lapsed", "It was already paid"], "correct": 1, "explanation": "Claims that fail scrubbing edits never reach the payer. The patient still gets a bill from the provider. Fix the errors, submit to the payer, and notify the patient it's being processed."},
    {"question": "You're collecting from a patient at 8:30 PM their local time. They say 'I'm going to report you.' Under FDCPA, are you compliant?", "answers": ["No — you can't call after 8 PM", "Yes — FDCPA allows calls between 8 AM and 9 PM", "No — you need written permission for evening calls", "Depends on the state"], "correct": 1, "explanation": "FDCPA permits calls between 8 AM and 9 PM in the debtor's local time zone. 8:30 PM is compliant. However, if the patient requests no more calls, you must honor that."},
    {"question": "An analyst posts a $5,000 payment to the wrong patient account. When discovered 2 days later, what's the correct process?", "answers": ["Leave it and make a note", "Reverse the posting from the incorrect account and reapply to the correct account with documentation", "Ask the patient to return the money", "Write off the difference"], "correct": 1, "explanation": "Misapplied payments must be reversed and correctly reposted. Document the error, reason, and correction. This maintains financial integrity and prevents patient confusion."},
    {"question": "A claim for a specialist visit is denied: 'Referral not on file.' The patient DID have a referral from their PCP. What likely happened?", "answers": ["The specialist didn't accept referrals", "The referral was obtained but never documented or attached to the claim during Pre-Service", "The patient's plan doesn't require referrals", "The PCP's referral expired"], "correct": 1, "explanation": "The referral existed but wasn't captured in the system during Pre-Registration. This is a Pre-Service failure. Resolution: obtain the referral documentation and resubmit."},
    {"question": "You're reviewing AR aging and notice 200 claims stuck at 75+ days for the same payer. What does this pattern suggest?", "answers": ["Normal processing time", "A systemic issue — possibly a payer contract dispute, system error, or changed submission requirements", "Those patients have bad insurance", "The claims are too old to collect"], "correct": 1, "explanation": "200 claims stuck at one payer = systemic issue, not individual errors. Investigate: Did the payer change submission rules? Is there a contract dispute? Is there a technical transmission failure?"}
  ],

  "master": [
    {"question": "Your team's denial rate jumped from 4% to 9% this month. 60% of the new denials are 'Prior Auth Required.' Leadership asks for root cause. What's your analysis?", "answers": ["Coders are making more errors", "A payer likely changed their authorization requirements and the Pre-Service team wasn't updated — verify which payer and which services now require auth", "Patients are choosing wrong insurance", "The clearinghouse is malfunctioning"], "correct": 1, "explanation": "A sudden spike in one denial type from specific payers = policy change. Root cause: identify which payer, which service codes, communicate to Pre-Service team, and implement authorization workflow updates."},
    {"question": "You discover that a specific provider's claims have a 35% denial rate vs. the team average of 5%. All denials cite 'insufficient documentation.' What's your recommendation?", "answers": ["Remove the provider from the network", "Conduct a targeted education session with that provider on documentation requirements — the issue is clinical documentation, not billing", "Hire more coders", "Appeal all 35%"], "correct": 1, "explanation": "Provider-specific documentation denials = education gap, not billing error. The provider needs coaching on what clinical documentation payers require. This is a collaboration opportunity between RCM and clinical."},
    {"question": "A $45,000 claim for surgery is denied as 'not medically necessary.' You have the prior authorization approval on file. What's your strongest appeal argument?", "answers": ["The patient needed it", "The payer pre-approved this service — cite the authorization number, date of approval, and reference their own medical necessity determination at time of auth", "Threaten legal action", "Offer to reduce the bill"], "correct": 1, "explanation": "If you have prior auth, the payer already determined medical necessity. Your appeal should cite their OWN approval (auth number + date) and argue they cannot retroactively reverse their determination."},
    {"question": "Leadership asks: 'Why did our Collections Yield drop from 94% to 88% this quarter?' Where do you start investigating?", "answers": ["Blame the collections team", "Analyze by payer, denial type, and AR aging bucket to identify which segment drove the drop — look for a new payer contract, staffing gap, or volume spike that overwhelmed capacity", "Reduce write-offs", "Hire more staff"], "correct": 1, "explanation": "Yield drops require segmented analysis. Is one payer paying less? Did denial volume spike? Is AR aging in one bucket? Data-driven root cause before solutions."},
    {"question": "You're building a business case for automating eligibility verification. What financial metric best justifies the investment?", "answers": ["Employee satisfaction", "Reduction in eligibility-related denials (show dollar value of denials prevented x average rework cost per denial)", "Number of verifications per day", "Software cost"], "correct": 1, "explanation": "Quantify: (current eligibility denial count) x (average cost to rework each denial, including staff time + delayed payment) = annual cost of NOT automating. Compare to tool cost."},
    {"question": "A patient's account shows: Original charge $8,000, Insurance paid $5,200, Contractual adjustment $2,100. Patient balance shows $700. But the patient insists their OOP max was hit. What do you investigate?", "answers": ["Accept the patient's claim and zero the balance", "Pull the EOB and cross-reference with the patient's accumulator — verify whether their OOP max was actually reached as of the date of service", "Send to collections", "Write it off as a courtesy"], "correct": 1, "explanation": "Check the payer's accumulator report showing the patient's deductible/OOP status as of the service date. If they truly hit OOP max, the payer owes additional payment. If not, the patient balance is correct."},
    {"question": "Your AR over 90 days increased by $400K this month. 70% of it is one payer. The payer says 'we never received the claims.' What's your next move?", "answers": ["Resubmit all claims and hope for the best", "Pull clearinghouse transmission receipts proving delivery, then escalate to payer with evidence of receipt — if no receipts exist, investigate transmission failures", "Write off the $400K", "Wait for the payer to find them"], "correct": 1, "explanation": "Clearinghouse receipts are your proof of submission. If they exist, you have leverage. If they don't, you have a transmission failure to fix. Either way, data comes first."},
    {"question": "A new analyst asks: 'Why do I need to understand coding if I work in collections?' What's the best explanation?", "answers": ["You don't — that's a different team's job", "Understanding WHY a claim was coded a certain way helps you resolve coding-related denials faster and communicate accurately with payers during appeals", "It's just company policy", "You might transfer to coding someday"], "correct": 1, "explanation": "Cross-functional knowledge = faster resolution. A collections analyst who understands coding can resolve CO-4 (modifier) or CO-16 (missing info) denials without waiting for the coding team."},
    {"question": "During a calibration session, you and another analyst score the same account differently. You gave it 5/6, they gave it 3/6. The disagreement is on 'Critical Thinking.' How should this be resolved?", "answers": ["Majority wins", "Review the specific documentation together — identify what evidence of reasoning/research each scorer looked for, align on the standard, and document the calibration decision for future reference", "Average the scores", "Ask a manager to decide"], "correct": 1, "explanation": "Calibration resolves scoring variance through evidence-based discussion, not authority. Review the work, identify the specific criteria gap, align, and document for consistency going forward."},
    {"question": "You notice that your PFS team resolves patient inquiries in an average of 3.2 calls per issue. Industry benchmark is 1.5 (FCR). What does this indicate and what would you propose?", "answers": ["Patients are being difficult", "Analysts lack the tools or authority to resolve issues on first contact — propose a root cause analysis of repeat-call reasons and empower front-line resolution for common scenarios", "We need more phone lines", "Reduce call time"], "correct": 1, "explanation": "3.2 calls vs. 1.5 benchmark = analysts can't resolve on first contact. Investigate: Are they lacking system access? Authority to waive fees? Knowledge of policies? Fix the root cause, not the symptom."}
  ]
};


// ═══ TRAIN THE TRAINER SCENARIOS ═══
// Tests whether players can teach others, adapt when situations change,
// solve problems without sacrificing business outcomes, and apply Leadership Principles.

const TRAINER_SCENARIOS = {
  "journeyman": [
    {"question": "A new hire asks you: 'Why can't I just call the payer and ask them to pay?' How do you explain the resolution process while showing Customer Obsession?", "answers": ["Tell them to just follow the SOP", "Explain that calling without research wastes the payer's time AND ours — we first check CARC/RARC, gather documentation, then contact with a clear ask. This respects everyone's time and gets faster results.", "Say the system doesn't allow calls", "Tell them to ask their manager"], "correct": 1, "explanation": "Customer Obsession applies to payers too — they are partners. Teaching structured research-first approach shows the new hire WHY the process exists, not just WHAT to do. This creates understanding, not just compliance."},
    {"question": "You trained an analyst on the write-off process last week. Today, they come to you with a $600 write-off that needs L7 approval per OM.BIL.POL.020, but the L7 is on PTO for 5 days. The timely filing deadline is in 4 days. What do you coach them to do?", "answers": ["Wait for the L7 to return", "Coach them to escalate to the backup approver or the L7's delegate — Bias for Action on a 2-way door. Document the urgency and get temporary approval to preserve the filing deadline.", "Write it off without approval", "Let it expire — it's the L7's fault"], "correct": 1, "explanation": "Bias for Action: This is time-sensitive and reversible (approval can be ratified after). Ownership: Don't let revenue expire because of a process gap. Teach the analyst to find the path, not wait for the default path to work."},
    {"question": "A junior analyst you mentored is now training their own mentee. The mentee asks a question your analyst doesn't know the answer to. Your analyst comes to you panicked. What do you tell them?", "answers": ["Give them the answer to relay", "Tell them it's okay to say 'I don't know — let me find out and get back to you.' Model that honesty builds trust. Then teach them how to research the answer so they can handle it next time.", "Tell them to make something up", "Say they should redirect to a manager"], "correct": 1, "explanation": "Earn Trust: Admitting gaps honestly is stronger than faking expertise. Teaching them HOW to find answers (Dive Deep) builds independence. The goal isn't having all answers — it's knowing how to find them."},
    {"question": "You're training a group on denial management. Mid-session, an analyst asks: 'What if the payer changes their auth requirements and we don't find out until claims start denying?' How do you address this — and what mechanism do you propose?", "answers": ["Say 'that's just how it is'", "Acknowledge it's a real risk, then propose a mechanism: weekly payer bulletin review, shared alert channel for new denial patterns, and a feedback loop where Post-Service flags upstream for Pre-Service updates. What mechanism prevents this from happening again?", "Tell them to escalate every time", "Say it's not their problem"], "correct": 1, "explanation": "Invent and Simplify + mechanism thinking: Don't just answer the question — build the system that prevents the problem. Teaching analysts to think in mechanisms (not one-time fixes) is how you scale quality."},
    {"question": "Your team's process just changed — a payer now requires authorization for services that previously didn't need it. An analyst trained under the OLD process submits 10 claims without auth. All deny. They feel terrible. How do you handle this as their coach?", "answers": ["Write them up for the errors", "Acknowledge the system failed them (the change wasn't communicated clearly), take ownership of the communication gap, then teach the new requirement and help them resubmit with auth. Blame the process, not the person.", "Tell them to be more careful next time", "Ignore it — 10 claims isn't a big deal"], "correct": 1, "explanation": "Ownership: If the process change wasn't communicated, that's a leadership/system failure, not an analyst failure. Earn Trust: Acknowledge the gap openly. Then teach forward — ensure they and all peers know the new requirement."}
  ],

  "master": [
    {"question": "Leadership says: 'Denial rate is 8%. Get it to 4%.' You know the root cause is split between coding errors (40%), missing auths (35%), and eligibility issues (25%). You only have bandwidth to fix ONE area this quarter. Which do you prioritize and why?", "answers": ["Fix all three equally", "Prioritize missing auths (35%) — it's the highest-impact fixable area. Coding errors need provider education (longer timeline). Auth gaps can be fixed with a process change this week. Think Big: solve the 35% now, build the coding education plan for next quarter.", "Start with eligibility since it's easiest", "Wait until you have bandwidth for all three"], "correct": 1, "explanation": "Pareto thinking + Bias for Action: Attack the largest controllable segment first. Missing auths can be fixed with a Pre-Service process update (fast). Coding education is important but takes longer. Don't let perfect be the enemy of good."},
    {"question": "A high-performing analyst wants to transfer to another team. Their knowledge is critical — they're the only person who knows a complex payer's appeal process. How do you handle this while respecting their growth AND protecting the business?", "answers": ["Block the transfer to retain knowledge", "Support their growth (Customer Obsession for your team members) AND protect the business: ask for 2-4 weeks overlap to document their knowledge into an SOP, cross-train a backup, and wish them well. Hire and Develop the Best means letting people grow.", "Let them go immediately", "Make them train someone but delay the transfer indefinitely"], "correct": 1, "explanation": "Hire and Develop the Best: Support growth. Ownership: Don't let critical knowledge live in one head. Insist on Mechanisms: documentation + cross-training before departure. Both goals can coexist."},
    {"question": "You're leading a calibration session. Two senior analysts strongly disagree on whether a specific note demonstrates 'Critical Thinking.' One says the analyst clearly researched; the other says the documentation doesn't prove it. The room is tense. What do you do?", "answers": ["Side with the more senior person", "Pause the emotion. Ask both to cite the specific words/evidence they're using to score. Write them on the board. If the evidence is ambiguous, that's a signal the scoring rubric needs clarification — turn the disagreement into a rubric improvement. Have Backbone; Disagree and Commit.", "Split the difference and move on", "Table it for later"], "correct": 1, "explanation": "Have Backbone; Disagree and Commit: Healthy debate is good. But ground it in evidence, not opinion. If reasonable people disagree, the rubric isn't clear enough — fix the rubric. This turns conflict into improvement."},
    {"question": "You trained your team on a new SOP. A month later, quality audits show only 60% adoption. The team says 'the old way was easier.' How do you drive adoption without just mandating compliance?", "answers": ["Mandate it and punish non-compliance", "Investigate WHY the old way feels easier. Is the new SOP adding unnecessary steps? Is training insufficient? Is the tool making it harder? Earn Trust by listening, then either simplify the SOP (Invent and Simplify) or retrain with better context on WHY it matters (connect to patient outcomes).", "Revert to the old process", "Add more monitoring"], "correct": 1, "explanation": "Dive Deep: 60% adoption means something is wrong — either the process, the training, or the motivation. Are Right, A Lot: Maybe the SOP needs simplification. Earn Trust: Listen before mandating. The goal is understanding, not just compliance."},
    {"question": "A critical system goes down during peak hours. Your team can't post payments or verify eligibility. Claims are piling up. You have 50 analysts sitting idle. What do you do RIGHT NOW while IT fixes the system?", "answers": ["Send everyone home", "Pivot the team to productive offline work: pull denied claims for manual research, conduct peer-to-peer training sessions on complex denial types, update SOP documentation, or have analysts review their own quality audit feedback. Frugality: never waste capacity. Bias for Action: adapt immediately.", "Wait for IT to fix it", "Have everyone send emails asking for updates"], "correct": 1, "explanation": "Bias for Action + Frugality: 50 analysts x idle hours = massive waste. Pivot to activities that don't require the system. This is leadership: you don't wait for conditions to be perfect. You create value regardless of constraints."},
    {"question": "Your organization is expanding to a new site. You need to replicate your team's quality standards there, but you can't physically be at both locations. How do you ensure consistency without being present?", "answers": ["Fly there every week", "Build mechanisms that don't depend on you: documented SOPs (not tribal knowledge), recorded training modules, calibration sessions across sites, shared quality dashboards visible to both locations, and a local champion trained to your standards. Mechanisms > heroics.", "Trust that they'll figure it out", "Send daily emails with instructions"], "correct": 1, "explanation": "Invent and Simplify + Mechanisms: Consistency at scale requires systems, not individuals. SOPs, recordings, cross-site calibrations, dashboards, and local champions — these scale. Your personal presence does not."}
  ]
};
